SELECT CURRENT_DATE(), CURRENT_TIMESTAMP();

CREATE OR REPLACE TABLE DW.DATE_DIM (
DATE_KEY NUMBER(10) PRIMARY KEY,
FULL_DATE DATE,
DAY_NUM NUMBER(3),
WEEKDAY_ABBR VARCHAR(3),
WEEKDAY_NUM NUMBER(1),
DAY_OF_YEAR_NUM NUMBER(3),
WEEK_OF_YEAR NUMBER(2),
MONTH_NUM NUMBER(2),
MONTH_ABBR VARCHAR(3),
QUARTER_NUM NUMBER(1),
QUARTER_NAME VARCHAR(3),
YEAR_NUM NUMBER(4),
FIRST_DAY_OF_MONTH DATE,
LAST_DAY_OF_MONTH DATE,
IS_WEEKEND VARCHAR(1)
);

CREATE OR REPLACE TABLE DW.TIME_DIM (
TIME_KEY NUMBER(4) PRIMARY KEY,
HOUR_NUM INTEGER,
MINUTE_NUM INTEGER,
TIME_24_HR STRING
);

CREATE OR REPLACE TABLE DW.CUSTOMER_DIM(
CUSTOMER_KEY NUMBER(10) PRIMARY KEY,
CUSTOMER_ID NUMBER(10),
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
COMPANY_NAME VARCHAR(100),
CITY VARCHAR(100)
STATE VARCHAR(50),
COUNTRY VARCHAR(50),
ZIP_CODE VARCHAR(10),
EMPLOYEE_ID NUMBER(10),
IS_ACTIVE VARCHAR(1) DEFAULT 'Y',
SOURCE_ID VARCHAR(50),
DATE_TO_WAREHOUSE DATETIME DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE SEQUENCE CUSTOMER_DIM_SEQ START = 1 INCREMENT = 1;
CREATE TABLE DW.ARTIST_DIM(
ARTIST_KEY NUMBER(10) PRIMARY KEY,
ARTIST_ID NUMBER(10),
ARTIST_NAME VARCHAR(150),
SOURCE_ID VARCHAR(50),
DATE_TO_WAREHOUSE DATETIME DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE SEQUENCE ARTIST_DIM_SEQ START = 1 INCREMENT = 1;

CREATE TABLE DW.SALES_FACT(
SALES_KEY NUMBER(10) PRIMARY KEY,
CUSTOMER_KEY NUMBER(10),
INVOICE_ID NUMBER(10),
DATE_DIM_KEY NUMBER(10),
TOTAL_SALE_AMT NUMBER(10,2),
SOURCE_ID VARCHAR(50),
DATE_TO_WAREHOUSE DATETIME DEFAULT CURRENT_TIMESTAMP()
);
--CLUSTER BY (SALE_DATE);


CREATE OR REPLACE SEQUENCE SALES_FACT_SEQ START = 1 INCREMENT = 1;