USE ROLE CHINOOK_ROLE;
USE WAREHOUSE CHINOOK_WH;
ALTER WAREHOUSE CHINOOK_WH RESUME;

USE DATABASE CHINOOK_DB;
USE SCHEMA CHINOOK_STAGE;

SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();
SHOW GRANTS ON SCHEMA CHINOOK_DB.CHINOOK_STAGE;
SHOW TABLES;
ALTER WAREHOUSE CHINOOK_WH RESUME;

SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();
SHOW GRANTS TO ROLE CHINOOK_ROLE;  